# Generated by Django 4.0.3 on 2022-12-16 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_commentrecipe_ingredientrecipe_recipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek'), (6, 'Sobota'), (7, 'Niedziela')], verbose_name='Dzień tygodnia')),
                ('meal_number', models.PositiveSmallIntegerField(choices=[(1, 'Śniadanie'), (2, 'Drugie śniadanie'), (3, 'Obiad'), (4, 'Podwieczorek'), (5, 'Kolacja')], verbose_name='Posiłek')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_schedules', to='food_app.recipe', verbose_name='Przepis')),
            ],
            options={
                'verbose_name': 'Przepis w planie',
                'verbose_name_plural': 'Przepisy w planie',
                'ordering': ['schedule', 'day_number', 'meal_number'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa planu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis planu')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Stworzył')),
                ('likes', models.ManyToManyField(related_name='likes_schedule', to=settings.AUTH_USER_MODEL, verbose_name='Polubienia')),
                ('recipes', models.ManyToManyField(related_name='schedules', through='food_app.RecipeSchedule', to='food_app.recipe', verbose_name='Przepisy')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plany',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='recipeschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_recipes', to='food_app.schedule', verbose_name='Plan'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeschedule',
            unique_together={('schedule', 'day_number', 'meal_number')},
        ),
    ]
